# Dockerfile to serve Next.js static export via Nginx
FROM nginx:alpine
LABEL org.opencontainers.image.title="picabord-static"
LABEL org.opencontainers.image.base.name="nginx:alpine"

# Copy the exported site (by default next export => out/)
COPY out/ /usr/share/nginx/html

# Remove default nginx config and use a basic config that serves static files
# or provide your custom config in ./nginx.conf
# COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
